Fission Product Model with Explicit Fission Products for all Depletable Components
terrapower/armi pull request #1067
Opened 2023-01-05 06:17 UTC by jakehader

## Description

Update the fission product model to fix a bug where all nuclides were not being initialized in non-fuel depletable components when using the `explicitFissionProducts` model. Add testing for the updated implementation.

---

## Checklist

- [x] This PR has only one purpose or idea.
- [x] Tests have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `setup.py`.

2023-01-05 22:11 UTC, mgjarrett commented on armi/physics/neutronics/fissionProductModel/fissionProductModel.py
> +                updatedNDens = {}
`updatedNDens` should start as `ndens`, not as an empty dict, right?
```suggestion
                updatedNDens = c.getNumberDensities()
```

2023-01-05 22:16 UTC, mgjarrett requested changes
I just have one suggested change. Otherwise, it looks good to me.

2023-01-05 22:52 UTC, john-science commented on armi/physics/neutronics/fissionProductModel/fissionProductModel.py
> +        .. note::
You have a `.. note::` within a `Notes`? 

I would ditch the `.. note::`, since you already have a section for notes. IMO.

2023-01-05 23:53 UTC, mgjarrett commented on armi/physics/neutronics/fissionProductModel/fissionProductModel.py
> +                    if nuc in ndens:
```suggestion
                    if nuc in updatedNDens:
```

2023-01-06 01:15 UTC, mgjarrett commented on armi/physics/neutronics/fissionProductModel/fissionProductModel.py
>          self.setAllBlockLFPs()
I think `interactDistributeState` should mirror the changes to `interactBOL`

2023-01-08 03:09 UTC, mgjarrett approved these changes

2023-01-09 21:10 UTC, opotowsky commented
This PR had an issue on Linux, where file paths are case sensitive. I edited the files / expected paths to be upper case, as is currently defined as the default. But now there are a mix of upper and lower case file path extensions in the test files. So as not to force this PR to solve even more problems, I made an issue about it: https://github.com/terrapower/armi/issues/1078

2023-01-09 21:28 UTC, opotowsky approved these changes
Reviewed the last portion of the PR written by Mike. No more missing dummy nuclides!

2023-01-09 21:33 UTC, merged

2023-01-11 00:26 UTC, mgjarrett commented on armi/nuclearDataIO/tests/.gitignore
> -*pmatrx*
In retrospect this maybe didn't need to change. But also, it maybe wasn't necessary to have these in the .gitignore in the first place, so it's not clear that it's a problem.