Adding axial expansion support for CRAs
terrapower/armi pull request #1226
Opened 2023-03-28 22:57 UTC by albeanth

## Description
This PR adds support for axial expansion of pin-type control rod assemblies (CRAs). The primary assumption with this approach is that all components axially expand upwards. This is a valid assumption as long as the z-elevation of the control bundle tip is relative to itself; i.e., simply placing the bundle at a prescribed z-elevation. This is in contrast to the case where the z-elevation of the control bundle is relative to the control rod driveline. In this case, the downward expansion of components within the control bundle becomes important and this approach is invalidated. 

This PR will remain in draft state until 1) unit tests are added to support CRA expansion, and 2) the effects on downstream applications have been quantified. 

---

## Checklist

- [x] This PR has only one purpose or idea.
- [ ] Tests have been added/updated to verify that the new/changed code works.

- [ ] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [ ] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [ ] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [ ] The documentation is still up-to-date in the `doc` folder.
- [ ] The dependencies are still up-to-date in `setup.py`.

2023-03-29 20:58 UTC, jakehader commented on armi/reactor/converters/axialExpansionChanger.py
> +        axialExpChanger.setAssembly(a)
That is unless it's standard and "just works"

2023-03-29 21:06 UTC, albeanth commented on armi/reactor/converters/axialExpansionChanger.py
> +        axialExpChanger.setAssembly(a)
It seems to be "just working". Though I'm still testing. I'll ping you directly.

2023-03-31 23:25 UTC, keckler requested changes
Easy enough. You need to add something to the changelog. I imagine this might change some results and confuse people.

2023-04-03 19:36 UTC, keckler approved these changes

2023-04-04 17:46 UTC, albeanth commented
Coverage drop appears to be coverage spray....

2023-04-18 17:16 UTC, john-science commented
@albeanth This is waiting on a downstream project.  So, short-term holding pattern.

2023-04-19 22:28 UTC, albeanth commented
This PR is ready, but I am converting to draft while we figure out downstream merge dependencies.

2023-04-25 15:03 UTC, merged