Fixed the float dimension decimals.
terrapower/armi pull request #1268
Opened 2023-05-17 22:53 UTC by jyang-TP

## Description

---

## Checklist

- [ ] This PR has only one purpose or idea.
- [ ] Tests have been added/updated to verify that the new/changed code works.

- [ ] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [ ] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [ ] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [ ] The documentation is still up-to-date in the `doc` folder.
- [ ] The dependencies are still up-to-date in `setup.py`.

2023-05-17 22:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/terrapower/armi?pullRequest=1268) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/terrapower/armi?pullRequest=1268) before we can accept your contribution.<br/><hr/>**jyang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/terrapower/armi?pullRequest=1268) it.</sub>

2023-05-18 18:22 UTC, keckler commented
Hi @jyang-TP , thanks for putting in this fix. Can you add a description to the PR so that reviewers or other interested parties can have some context on why this PR is needed and what it is meant to do? Thanks!

2023-05-18 20:26 UTC, keckler requested changes
It seems that we have a problem here. Check out this PR that was merged just a couple months ago: https://github.com/terrapower/armi/pull/1225

Your change is essentially reverting the PR that I point out, which was implemented to fix a bug with the uniform mesh converter. It actually says as much in the docstring of the method that you changed (`findAllmeshPoints()`).

So it looks like we have conflicting needs here, where the uniform mesh converter needs less digits of precision, but your needs require more.

In order to find a solution that will satisfy both your needs and @albeanth 's needs, I think it would be very helpful to add a bit more context to this PR that outlines why you are trying to make this change.

2023-05-18 20:32 UTC, albeanth commented
@jyang-TP or it your PR isn't ready, please mark it as a draft. When the PR is open, reviewers will interpret it as "ready-to-go right now" and start reviewing it.

2023-05-30 20:04 UTC, closed without merging