Moving missing file warning to debug
terrapower/armi pull request #1346
Opened 2023-07-17 18:05 UTC by john-science

## What is the change?

This moves a "missing file" warning from `INFO` to `DEBUG` when cloning a case.

> The only problem I have here, is I don't know how to test this with all the different workflows, to make sure it doesn't cause anyone problems.  Ideas?

## Why is the change being made?

This is to close #1304 .

It is a request, because users don't like seeing the extra warning on the command line.

---

## Checklist

- [X] This PR has only one purpose or idea.
- [X] Tests have been added/updated to verify that the new/changed code works.

- [X] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [X] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [X] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any important changes.
- [X] The documentation is still up-to-date in the `doc` folder.
- [X] The dependencies are still up-to-date in `setup.py`.

2023-07-17 20:18 UTC, keckler reviewed
Not sure whether or not this satisfies the original request from @onufer , so I'm going to abstain from approving.

2023-09-21 21:54 UTC, opotowsky approved these changes
Following Chris' comment, I have confirmed offline that this does satisfy Mark's request. He's happy to just have the warning print for higher verbosity runs.

The code change is easy enough, approved!

2023-09-21 23:15 UTC, onufer commented
this does not solve the issue. if the issue was just a message, i wouldn't have bothered to make a ticket, or i would have changed there verbosity myself. sorry the original issue was unclear... working on getting you a valid traceback. @opotowsky told me the issue so i think i need to talk with her

2023-09-21 23:15 UTC, onufer requested changes
print message verbosity was not the problem. working to get you a traceback...

2023-09-21 23:20 UTC, closed without merging