Add Thermal Scattering information
terrapower/armi pull request #140
Opened 2020-08-27 17:07 UTC by ntouran

Thermal scattering laws are important nearly all thermal reactors. This
change adds a class to the nucDirectory package to represent these laws,
and populates a module-level lookup table with some common ones. A class
attribute on Material is also added so that Material designers can
activate certain TSLs. Given this information, physics kernel authors
can detect the need for TSL treatment and implement it as necessary.

2020-08-27 18:35 UTC, ntouran commented
Huh not seeing that unit test failure on my runs unless I run through tox. Using pytest -n12 does not hit it. Maybe a parallel issue with some other test re-building the nuclideBases? Probably.

2020-09-09 20:42 UTC, youngmit requested changes
My main concern is with how `getNuclideThermalScatteringData()` will function in general, and if it is fully-baked enough to encourage its broad use. At the very least, we should consider how it behaves in all of the combination of cases scattering law/no scattering law.

More fundamentally, I am wondering if there is an opportunity to simplify/merge this with the broader concept of `NuclideBases` and make, for instance `ThermalScattering(nb.byName["C"], SIC)` be mostly indistinguishable from `nuclideNases.byName["C"]`, except for when something thermal scattering-aware starts asking the right questions. Definitely beyond the scope of this branch, and would require some de-globalization work of NuclideBases before we could speak intelligently about it. Just want to make sure it's on your radar I guess.

2020-09-11 18:04 UTC, ntouran commented on doc/user/tutorials/making_your_first_app.rst
> +    information on materials as well.
I'll just delete it for now

2020-09-11 18:06 UTC, ntouran commented on armi/nucDirectory/nuclideBases.py
> +    should be implemented so the objects don't have to change identity.
added a note

2020-09-11 18:08 UTC, ntouran commented on armi/nucDirectory/thermalScattering.py
> +def getNuclideThermalScatteringData(armiObj):
Here's an example, from the dragon plugin (under review):

```python

    def getMixVector(self):
        """
        Generate mixture composition table.
        """
        nucs = self.options.nuclides
        nucData = []
        numberDensities = self.armiObj.getNuclideNumberDensities(nucs)
        thermalScatteringInfo = tsl.getNuclideThermalScatteringData(self.armiObj)
        if not any(numberDensities):
            # This is an empty armiObj. Can happen with zero-volume dummy components.
            # This writer's job is to accurately reflect the state of the reactor,
            # we simply return an empty set of number densities.
            return []
        for nucName, nDens in zip(nucs, numberDensities):
            nuclideBase = nb.byName[nucName]
            if isinstance(nuclideBase, (nb.LumpNuclideBase, nb.DummyNuclideBase),):
                # This skips lumped fission products.
                continue

            nucData.append(
                MixtureNuclide(
                    armiName=nuclideBase.label,
                    xsid=self.options.xsID,
                    dragName=getDragLibNucID(nuclideBase, thermalScatteringInfo),
                    ndens=nDens,
                    selfShield=self.getSelfShieldingFlag(nuclideBase, nDens),
                )
            )
        return nucData
```

2020-09-11 18:09 UTC, ntouran commented on armi/nucDirectory/thermalScattering.py
> +    Make a mapping between nuclideBases in an armiObj and relevant thermal scattering laws.
great point. We should explicitly handle that situation, or error.

2020-09-14 18:20 UTC, youngmit approved these changes
Thanks!

2020-09-16 23:45 UTC, merged