Add cornersUp property to HexGrid.
terrapower/armi pull request #1648
Opened 2024-02-15 20:09 UTC by mgjarrett

## What is the change?

Add a `cornersUp` property to `HexGrid` to check orientation before plotting.

## Why is the change being made?

There are many places where the code assumes a given orientation for a hex grid, but there are two orientations that are both valid. This property is an easy way for a user or developer to check the orientation of a `HexGrid`. The check is implemented by checking the `HexGrid.unitSteps` attribute.

- This should solve #1421 
- The `cornersUp` property might be used to resolve issues raised in #1278 and #1284

---

## Checklist

- [ ] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [ ] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify that the new/changed code works.

- [ ] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [ ] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [ ] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any important changes.
- [ ] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [ ] If any [requirements](https://terrapower.github.io/armi/developer/tooling.html#watch-for-requirements) were affected, mention it in the [release notes](https://terrapower.github.io/armi/release/index.html).
- [ ] The dependencies are still up-to-date in `pyproject.toml`.

2024-02-15 20:11 UTC, mgjarrett commented
Note: others may be working on parallel solutions to the issues linked in the PR description. I'm just trying to share the bare-bones outline of a path we could take to fix the problem; I'm not necessarily saying _this_ PR needs to be merged.

2024-02-15 21:34 UTC, john-science commented
As I said in the other ticket (https://github.com/terrapower/armi/issues/1278), I have am working on a PR that fixes two different `HexGrid` bugs.  I "assigned" that ticket to me to reduce code duplication.  Sorry about that.

I like your property, and haven't looked at your plotting fix yet.

2024-02-25 17:09 UTC, keckler requested changes
Thanks @mgjarrett for trying these changes! I think there are a couple things that need to be fixed before we can maybe merge it.

Ultimately I think we can make it work, but _man_ this `plotBlockDiagram` method is frustratingly specific and fragile. In the longer term, it might make sense to split the method into two methods to handle the cases of hexagonal vs cartesian assemblies independently. I think that would make things a lot cleaner. Not asking for you to do this now, just maybe something to think about in a later ticket.

2024-02-25 17:09 UTC, keckler commented on armi/utils/plotting.py
>          if component.getDimension("ip", cold=cold) != 0:
The changes that you made are only inside of this `if` clause. This means the rotation will only be applied to the hexes that have an `ip`. 

The other major hexagon that doesn't have an `ip` is the `DerivedShape` that often represents the coolant. This one doesn't get rotated by the logic that you've implemented. Here is a diagram that I've produced using your changes:
![image](https://github.com/terrapower/armi/assets/21959600/deb26d2f-cc1a-405c-b058-b8329b1ed5e2)

2024-02-25 17:12 UTC, keckler commented
I might also suggest changing the name of the PR, since this PR is _mostly_ about fixing the block diagrams, IMO. #1649 includes the same changes related to the new `cornersUp` property.

2024-02-26 16:48 UTC, mgjarrett commented
@keckler thanks for the review.

My goal here was just to show in code what the outline of my idea for fixing the problem was; I thought it would be easier than describing it in words. I knew @john-science was working on this issue, so I wanted to wait and see what the code looked like after he finished his work.

Now that he's fixed most of the confusion between flats/corners up, I think it makes sense to change the scope of this to just fixing `plotBlockDiagram`, as you suggest. I'll take a stab at it when I get a chance today.

2024-02-26 20:03 UTC, mgjarrett commented
@keckler I incorporated your comments; the plots look good now (at least for a flats up block; I don't have a corners up block handy for testing).

![image](https://github.com/terrapower/armi/assets/11633797/ad1363a5-1f85-4035-810c-0779792e0d2b)

I merged #1649 into this branch locally and tested it, and the plotting still works. So once #1649 is merged into main, this PR can be merged with main and it should all work out.

2024-02-26 20:38 UTC, mgjarrett commented
I thought about adding unit tests, but this is mostly plotting stuff that is difficult to test directly.

2024-02-26 20:45 UTC, keckler commented on armi/utils/plotting.py
> +            Amount of counterclockwise rotation (in degrees) for a hexagon component patch
```suggestion
            Amount of counterclockwise rotation (in degrees) for a hexagon component patch. 0 degrees
            corresponds to a hexagon with its corner pointing up.
```

2024-02-26 20:48 UTC, keckler commented on armi/utils/plotting.py
> +            Amount of counterclockwise rotation (in degrees) for a hexagon component patch
Please correct the suggest wording if I got it backwards.

2024-02-26 21:01 UTC, keckler commented on armi/utils/plotting.py
>          if component.getDimension("ip", cold=cold) != 0:
The pictures appear to be fixed for me as well.

2024-02-26 21:02 UTC, keckler approved these changes
Thank you for working on this!

2024-02-27 22:32 UTC, mgjarrett commented
Hmm still needs some work for corners up. I think the plotting is right, but the generation of the pin grid is wrong.

![image](https://github.com/terrapower/armi/assets/11633797/4083c7cb-c00a-4c19-85ee-ee316418b356)

2024-03-22 23:26 UTC, mgjarrett commented
> Hmm still needs some work for corners up. I think the plotting is right, but the generation of the pin grid is wrong.
> 
> ![image](https://private-user-images.githubusercontent.com/11633797/308357040-4083c7cb-c00a-4c19-85ee-ee316418b356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNTAwMDQsIm5iZiI6MTcxMTE0OTcwNCwicGF0aCI6Ii8xMTYzMzc5Ny8zMDgzNTcwNDAtNDA4M2M3Y2ItYzAwYS00YzE5LTg1ZWUtZWUzMTY0MThiMzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDIzMjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NDE3M2UyNWU4MGZiODA3NDFlMzZmOTU2ZDRhMjg2NzhkMzMyMzNlZjg2MDRmNDFlNDA4NjFhYmQ5ODdmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S2Y9z_KufFRLkgDCRwjj5gehkwyiknj7GNPbnLnkSls)

I looked into this problem a little more. There's nothing wrong with the plotting code necessarily, it's just that `block.autoCreateSpatialGrids()` only works if the block is "flats up". I tried to figure out a way to make it work with `cornersUp` blocks, but the block doesn't know what kind of grid it is going into when the local pin coordinates are auto-created.

Maybe we could check the orientation of the pin coordinates once the block has been placed in a `core` grid, and then rotate the pins 30 degrees counterclockwise if necessary? It's not a great solution, but it's the only thing I can think of.

2024-10-04 22:59 UTC, mgjarrett commented
this will be superseded by #1926 -- assuming that is going to be merged, I will close this one

2024-10-04 22:59 UTC, closed without merging

2024-10-04 23:34 UTC, john-science commented
> this will be superseded by #1926 -- assuming that is going to be merged, I will close this one

Oh, I'm sorry Michael.  We made a list of bug tickets yesterday, and I was just going through them, trying to solve the low-hanging fruit.

I just didn't see this PR, and forgot. Sorry!