Update `block.rotatePins()` to take an optional `numPins` argument
terrapower/armi pull request #1859
Opened 2024-09-06 11:15 UTC by mgjarrett

## What is the change?

Add an optional `numPins` argument to the `block.rotatePins()` method to specify the number of pin indices to be rotated.

## Why is the change being made?

`block.rotatePins()` computes a mapping for hex lattice pin indices after having been rotated by some multiple of 60 degrees. Previously, the `rotatePins()` method just inferred the number of pins based on the number of components with `Flags.CLAD`. This argument provides more flexibility to the user. There are at least two cases where this new argument could be useful:

1. The block doesn't have any `CLAD` components (e.g., a solid steel reflector slug)
2. The block is missing pins (or not all of the pins have a `CLAD` component). The math for mapping the indices only works if the number of pins fits exactly into a regular hex lattice (19, 37, 61, 91, etc.)

---

## Checklist

- [x] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [ ] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify any new/changed code.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [ ] The [release notes](https://terrapower.github.io/armi/developer/tooling.html#add-release-notes) have been updated if necessary.
- [x] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `pyproject.toml`.

2024-09-06 11:42 UTC, mgjarrett commented
Note that I just realized #1846 will make `rotatePins` private, so if that is merged first then I would have to update the release notes, which currently mark this as being an API change.

2024-09-06 16:55 UTC, drewj-tp commented
The `justCompute=True` behavior is something that I think could be moved off of `HexBlock.rotatePins`. The place it's used in ARMI at least is just to find post-rotation location of pins to minimize burnup

https://github.com/terrapower/armi/blob/f5267e0cc332ac9c97e8fe1c4e49e28076455399/armi/physics/fuelCycle/hexAssemblyFuelMgmtUtils.py#L105

Which feels like overkill to emulate rotating every single pin in a block just to see where one pin would end up. So I put some of the code in `armi.utils.hexagon` in https://github.com/terrapower/armi/pull/1846/commits/afd452893febe9f46f7c007ddf5a27e0aa381af9.

If there are other needs for `justCompute=True`, let me know and I can try to fold them in to #1846 or we can put them in a new ticket

2024-09-07 00:07 UTC, mgjarrett commented
Marking this as draft until #1846 is merged; this PR will be updated after that

2024-09-13 17:11 UTC, mgjarrett commented
after #1846 made `_rotatePins` private, it no longer makes sense to add the optional `numPins` argument to this function, because users won't be calling this function directly anyway.

However, I think it could still be worthwhile to make the determination of the number of pins more robust. `Block` has a `getNumPins` method that is more robust than the one-liner used.

https://github.com/terrapower/armi/blob/abd1db4adfa0c536f9bf9f08f0f1e8b74b1cd0d7/armi/reactor/blocks.py#L1047-L1079

 Is there any reason not to use `getNumPins` here?

https://github.com/terrapower/armi/blob/abd1db4adfa0c536f9bf9f08f0f1e8b74b1cd0d7/armi/reactor/blocks.py#L2141

2024-09-17 22:38 UTC, john-science commented on doc/release/0.4.rst
> +#. Use ``Block.getNumPins()`` in HexBlock._rotatePins() (`PR#1859 <https://github.com/terrapower/armi/pull/1859>`_)
```suggestion
#. Use ``Block.getNumPins()`` in ``HexBlock._rotatePins()``. (`PR#1859 <https://github.com/terrapower/armi/pull/1859>`_)
```

2024-10-02 21:02 UTC, drewj-tp requested changes
Can you update the PR description accordingly? The `Block.rotatePins` method has been removed, but the PR description discusses changes to it

2024-10-02 21:02 UTC, drewj-tp commented on armi/reactor/blocks.py
> +                numPins = hexRings[i + 1]
So this is trying to find the number of pins in a full hex lattice in the event we have fewer pins? So if I have two rings of pins with the center spot missing, `numPins` would be six, but this logic would round up to seven for two full rings?

If that's the case, could these two functions be helpful?

https://github.com/terrapower/armi/blob/f1f3dbea05c2564404a03d8e053f72c2af15daa9/armi/utils/hexagon.py#L107-L111

https://github.com/terrapower/armi/blob/f1f3dbea05c2564404a03d8e053f72c2af15daa9/armi/utils/hexagon.py#L150-L151

like
```python
numPins = self.getNumPins()
numRings = numRingsToHoldNumCells(numPins)
fullNumPins = totalPositionsUpToRing(numRings)
```

2024-10-03 23:16 UTC, john-science approved these changes

2024-10-04 15:21 UTC, drewj-tp approved these changes

2024-10-04 16:32 UTC, merged