Add some missing nuclides from nuclides.dat
terrapower/armi pull request #1903
Opened 2024-09-25 14:56 UTC by albeanth

## What is the change?
A simple change to add some nuclides to nuclides.dat to support downstream analysis. 

## Why is the change being made?
It's good to account for all the nuclides that one _might_ care about. 

---

## Checklist

- [x] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- ~[Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify any new/changed code.~

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [ ] The [release notes](https://terrapower.github.io/armi/developer/tooling.html#add-release-notes) have been updated if necessary.
- ~The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.~
- ~The dependencies are still up-to-date in `pyproject.toml`.~

2024-09-25 14:57 UTC, albeanth commented
@john-science just a heads up. This should be pretty simple to push through. I can handle internal QA-related things. I've pinged @jakehader and Connor for an SME review.

2024-09-25 16:30 UTC, john-science commented
@albeanth Can you run the big internal suite of unit tests against this PR? Obviously, functionally, this PR shouldn't make a big difference. But I imagine some "diffs" popping up in your internal integration tests, and who knows maybe someone is checking an exact number in their unit tests somewhere.

2024-09-26 22:04 UTC, linconnor requested changes
Two lines don't look right to me. Please double check.
line 2914 now is 70  171 188 0 should be -> 70  118 188 0
line 3092 now is 73  120 195 0 should be -> 73  122 195 0
 
Additionally, it's good to add the source of these added lines, and modify the sentence at the beginning of the file "This file contains a set of 4614 nuclides and their associated metadata"  4614 -> 4624

2024-09-26 22:35 UTC, albeanth commented on armi/resources/nuclides.dat
> +70  171 188 0   YB    1.87966850000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
```suggestion
70  118 188 0   YB    1.87966850000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
```

2024-09-26 22:36 UTC, albeanth commented on armi/resources/nuclides.dat
> +73  120 195 0   TA    1.94972540000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
```suggestion
73  122 195 0   TA    1.94972540000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
```

2024-09-26 22:53 UTC, linconnor approved these changes
The added nuclides data look good to me.

2024-10-19 02:14 UTC, jakehader approved these changes

2024-10-20 02:15 UTC, john-science commented
I can verify but not validate this change.

Holler when you guys want to merge this.

2024-10-21 16:43 UTC, jakehader commented on armi/resources/nuclides.dat
> +70  118 188 0   YB    1.87966850000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
Checked

2024-10-21 16:44 UTC, jakehader commented on armi/resources/nuclides.dat
> +71  120 191 0   LU    1.90971560000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
Checked

2024-10-21 16:45 UTC, jakehader commented on armi/resources/nuclides.dat
> +73  122 195 0   TA    1.94972540000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
Checked

2024-10-21 16:46 UTC, jakehader commented on armi/resources/nuclides.dat
> +96  134 230 0   CM    2.30046089000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
Checked

2024-10-21 16:46 UTC, jakehader commented on armi/resources/nuclides.dat
> +97  134 231 0   BK    2.31045560000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
Checked

2024-10-21 16:47 UTC, jakehader commented on armi/resources/nuclides.dat
> +101 142 243 0   MD    2.43070833000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
Checked

2024-10-21 16:47 UTC, jakehader commented on armi/resources/nuclides.dat
> +103 145 248 0   LR    2.48074127000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
Checked

2024-10-21 16:47 UTC, jakehader commented on armi/resources/nuclides.dat
> +105 147 252 0   DB    2.52076730000e+02 0.00000000000e+00 1.11110000000e+01 0.000000
Checked

2024-10-21 17:08 UTC, jakehader commented
> I can verify but not validate this change.
> 
> Holler when you guys want to merge this.

I checked them @john-science.

2024-10-24 14:11 UTC, john-science commented
@jakehader @albeanth This appears complete to me.  Status?

2024-10-24 16:14 UTC, merged