Make it possible to add interfaces with the same function
terrapower/armi pull request #307
Opened 2021-05-26 23:47 UTC by chris10mckenz

Originally addInterface would raise an exception when the Interface
stack already contained an Interface with the same function as the one
passed into it. This was limiting when you had different plug-ins but
wanted the right Interface to take precedence.
So, now it adds an Interface even if it has the same function as one
previously if the new Interface is a subclass of the current Interface
with that function. This keeps the Interface that is more derived and
removes the old Interface. This still throws an exception if the new
Interface has the same function but shares no inheritance with the old
Interface. If the old Interface is instead a subclass of the new
Interface, neither interface is removed or added.

2021-05-26 23:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/terrapower/armi?pullRequest=307) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/terrapower/armi?pullRequest=307) before we can accept your contribution.<br/><hr/>**Christen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/terrapower/armi?pullRequest=307) it.</sub>

2021-05-27 15:05 UTC, youngmit requested changes
Just a couple of minor things. Mostly that it would be nice to report something to the user for both the more- and less-derived cases.

2021-05-27 15:05 UTC, youngmit commented on armi/operators/operator.py
> +                self.removeInterface(iFunc)
Which of these branches gets taken is I think just a matter of the order in which a fist full of Interfaces are added. So I think it makes sense to report something to the user either way. Could you add a `runLog` message saying that we are replacing the existing interface with the new one?

2021-05-27 15:05 UTC, youngmit commented on armi/operators/tests/test_operators.py
> +    subprocess.call(args)"""
This is a bit confusing as a string literal. Kinda looks like a docstring? Probably better to make it a proper comment.

2021-05-27 15:14 UTC, chris10mckenz commented
#307

2021-05-27 15:55 UTC, merged