Add Report Content Structure
terrapower/armi pull request #361
Opened 2021-08-04 18:58 UTC by chris10mckenz

Add a new way of compiling report content. In general, ReportContent is
the way report content is stored. It is made up of ReportNodes(Sections, Tables,
Images, TimeSeries(the storage representation for eventual graph output) and 
HtmlElements. It is converted to an html page output when writeReports()
 is called and renders each of it's items into html elements. In addition, 
getReportContents() is a plugin hook that collects contents from different
 plugins over the course of collecting data for the report. 
This allows for different plugins to either add to an existing Section/Table/etc
 or create new Section/Tables/etc

Currently this collection happens in the entry point for
reports, that allows a user to either provide a settings yaml file or an
h5 file to create report content.

In addition, created developer documentation for these items within
reports.rst. Also, added added a section for accessing the report entry
point within the User Documentation section.

2021-08-04 23:15 UTC, youngmit requested changes
A high-level thing is function naming. There are some functions in newReportUtils.py that serve mostly to insert contents into the passed `report` argument. I would make sure that these are named consistently (I recommend a `insert[Whatever]()` convention). Some of them are returning some ReportNode stuff that is expected to be inserted by the caller. Those I would also name consistently (`get[Whatever]()`?). There are also some that seem to add stuff to the report and return something. I think it probably best to steer clear of that pattern because it's rather confusing to have a function with side effects on an argument, but also produces a value. I suspect the return values in these cases are not used anyways.

There some functions in the old reportUtils module named `whatever2()` is there a reason why they are there, instead of just being in newReportUtils? The ultimate goal will be to remove reportUtils and replace it with newReportUtils, so we probably dont want to mix the two worlds too much, or have anything in old reportUtils that we can't just remove without breaking the new reports.

2021-08-04 23:15 UTC, youngmit commented on armi/bookkeeping/report/reportingUtils.py
> +def makeCoreDesignReport2(core, cs, report):
pull this into newReportUtils?

2021-08-04 23:15 UTC, youngmit commented on armi/physics/neutronics/__init__.py
> +import base64
not used

2021-08-04 23:15 UTC, youngmit commented on armi/physics/neutronics/reportConstants.py
> +INITIAL_CORE_FUEL_ASSEMBLY = "Initial Core Fuel Assembly Count"
I would just put these straight into neutronics/reports.py

2021-08-04 23:15 UTC, youngmit commented on armi/plugins.py
> +from h5py._hl.files import File
unused

2021-08-04 23:15 UTC, youngmit commented on armi/plugins.py
> +
I would add a link to the developer docs that you wrote.

2021-08-05 15:51 UTC, chris10mckenz commented on armi/bookkeeping/newReportUtils.py
> +from htmltree import Table as HtmlTable
I moved table of contents into newReports so don't even need to import here anymore. But yes, also only import htmltree in general now.

2021-08-05 17:38 UTC, youngmit requested changes
A few more minor things.

2021-08-05 17:38 UTC, youngmit commented on armi/bookkeeping/newReportUtils.py
> +def setDimensionReport(comp):
If this returns a Table, lets call it, `get`, or `create`, rather than `set`. `set` implies side effects.

2021-08-05 17:38 UTC, youngmit commented on armi/bookkeeping/newReportUtils.py
> +def makeCoreAndAssemblyMaps(
insert?

2021-08-05 17:57 UTC, youngmit requested changes

2021-08-05 17:57 UTC, youngmit commented on armi/cli/reportsEntryPoint.py
> +                            stage = ReportStage.Standard
Is this right? Seems like you still need standard processing for the last node, but extra end processing, too. So always do Standard, then outside the loop do another call to the plugin hood, passing `End`

2021-08-05 22:59 UTC, youngmit approved these changes

2021-08-05 23:15 UTC, merged