Add energy group structure for ANL21 used in photon transport
terrapower/armi pull request #994
Opened 2022-11-23 16:59 UTC by keckler

## Description

This just adds another typical energy group structure to our physics.neutronics.energyGroups module. The added structure is common for photon transport.

---

## Checklist

- [x] This PR has only one purpose or idea.
- [ ] Tests have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `setup.py`.

2022-11-23 17:08 UTC, jakehader commented
Thanks @keckler - can you add the ANL94 group for photons too?

2022-11-23 17:20 UTC, keckler commented
@jakehader Sure, done!

2022-11-23 21:04 UTC, jakehader requested changes
Numbers look correct! Minor comment.

2022-11-23 21:04 UTC, jakehader commented on armi/physics/neutronics/energyGroups.py
> +GROUP_STRUCTURE["ANL21PHOTON"] = [
This is typically denoted as `"ANL21G"` recommend updating.

2022-11-23 21:04 UTC, jakehader commented on armi/physics/neutronics/energyGroups.py
> +GROUP_STRUCTURE["ANL94PHOTON"] = [
This is typically denoted as `"ANL94G"` recommend updating.

2022-11-23 21:24 UTC, keckler commented
@jakehader Names are fixed.

2022-11-24 03:51 UTC, jakehader approved these changes

2022-11-24 03:51 UTC, merged